### ISSUE TITLE
Action installation is failing

### ISSUE THREAD

**Issue by jyash97** [hallee/eslint-action#12]
Hey firstly thanks for creating an awesome Action ✨ 

Usage:

```
name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

Facing the below issue: 
![image](https://user-images.githubusercontent.com/22376783/82444366-bf2cbd00-9ac0-11ea-843e-a0ffb8071e63.png)
