### ISSUE TITLE
2 checks instead of 1 with config shown in README

### ISSUE THREAD

**Issue by pcowgill** [hallee/eslint-action#23]
Is there a way to have this action only show up as 1 "check"? It shows up as two with the config shown in the README for this repo. Thanks!

![Screenshot 2020-06-01 10 07 06](https://user-images.githubusercontent.com/2731712/83422851-c4a6d300-a3ef-11ea-9c3a-063292d21476.png)

![Screenshot 2020-06-01 10 08 15](https://user-images.githubusercontent.com/2731712/83422930-dc7e5700-a3ef-11ea-8214-2c2867dc6c93.png)

**Comment by pcowgill** [comment]
@hallee Do you know if others are experiencing this issue? Do you when you use this action? Thanks!

**Comment by hallee** [comment]
Hey, I assigned myself to this issue 9 days ago, but haven't had time to work on it. Pinging me isn't helpful, but if you'd like to contribute, feel free to make a PR yourself!

**Comment by flut1** [comment]
@pcowgill I'm experiencing the same issue. Unfortunately not on a public repository but let me know if I can answer any questions that might help resolve the issue

**Comment by tobiasdiez** [comment]
Here is a public repo where this problem occurs (with the default config as in the readme): https://github.com/Zettlr/Zettlr/pull/1132/checks?check_run_id=925339946

**Comment by flut1** [comment]
Finally figured out what is happening here. Github's `actions/setup-node` (which @tobiasdiez is also using in the example they linked) automatically parses the `stdout` for issues and lists that as a separate check. I don't think this was always the case but if I understand correctly this is a feature that was added later. This behavior isn't particularly well documented, but they call them "problem matchers". So if you run `eslint` from a Github action, Github automatically parses and recognizes the console output of eslint. 

Unfortunately I think that makes this project rather obsolete? Because you can just run `eslint` from an action `.yml` and it will work out of the box. Though please feel free to correct me if I'm missing something. Here's the setup I use for my project now, and it works for me:

```
name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        # ~~~ CACHING ~~~
        # The following is just to do caching of yarn and eslint, it's not necessary to get linting to work
        # I would recommend first trying without

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache action
        uses: actions/cache@v2
        id: yarn-cache 
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./.eslintcache
          key: ${{ runner.os }}-yarn-lint-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-lint-

       # ~~~ END CACHING ~~~

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
```

(note that I have a `lint` script in my `package.json`: `eslint . --cache`)
